### ISSUE TITLE
Implementation of wavelet

### ISSUE THREAD

**Issue by nshervt** [dmzou/SCAT#2]
In your paper, you have mentioned that you are using the Shannon wavelets for the numerical results. In the code you provided, `propLayerHaar` is using Shannon wavelets but you do scattering using Paley-Littlewood wavelet in `propLayer` and never seem to use `propLayerHaar`. I was wondering were this Paley-Littlewood wavelets come from and how does it work. Thanks!

**Comment by dmzou** [comment]
Hello!

This is a problem with naming. Actually `propLayer` is running the Shannon wavelet.  `propLayerHaar` is running Haar, but since implemented in the spectral domain it looks like Shannon.
