### ISSUE TITLE
Do element of lamb can be negative numbers?

### ISSUE THREAD

**Issue by SeongJinAhn** [dmzou/SCAT#3]
https://github.com/dmzou/SCAT/blob/40188296b034a2b81b480966961f20b9617fc192/scat.py#L17

Hi! I have a question in your implementation.
I  your paper it is said that 0 = λ0 ≤ · · · ≤ λN−1.
However in lamb, there are some negative eigenvalues whose absolute values are very small.
But when code pop y[0], these negative eigenvalues are also included in y_out.
Is there reasons you did this way?

**Comment by dmzou** [comment]
Hello!
For a graph Laplace, it should be the case that all the eigenvalues are nonnegative. If you see a small negative eigenvalue, it should be the floating error.
