### ISSUE TITLE
Link prediction evaluation bug

### ISSUE THREAD

**Issue by malkin1729** [dmzou/SCAT#4]
Hello,

We think there may be an issue in the evaluation code for link prediction on Cora/CiteSeer/PubMed datasets. Specifically, the line `for i in range(val_edges_false.shape[0]):`, where the PCA features for the negative test edges are being filled, should possibly read `for i in range(test_edges_false.shape[0]):`. Because there are twice as many test edges as val edges, with the current code, half of the negative test edges have their features set to 0. 

This causes half of the negative test edges to be predicted in the same way independently of their features, which leads to an incorrect shift in the test scores. For example, when running the link prediction experiment with the default settings, e.g., `python trainCora.py -s S -d citeseer`, the test accuracy is typically ~3% higher than the validation accuracy on any random split, which is not to be expected with randomly sampled val and test edges. 

However, if that line is changed as we suggest, then the validation accuracies and test accuracies become the same, averaged over many runs with random data splits. For example, with that change, the average test scores on the CiteSeer dataset turn out to be closer to 94% than to the 97% reported in Table II.

The link to the code: https://github.com/dmzou/SCAT/blob/40188296b034a2b81b480966961f20b9617fc192/trainCora.py#L270

**Comment by dmzou** [comment]
That's true. Thanks very much for finding this out. Corrected the code.
