### ISSUE TITLE
Graph and signal generation experiments

### ISSUE THREAD

**Issue by xiangsheng1325** [dmzou/SCAT#5]
Hi! I found that signal generation experiments can be reproduced easily by the following command:
`python trainFashion.py -s D -g W`
However, the graph generation experiments seem to be just ignoring the warning messages of the former, so that there is no graph generation experiment?
Actually I think the trainFashion.py should be replaced with trainQM9.py.

**Comment by dmzou** [comment]
That's true. Thank you!
